# Copié vers /etc/sddm.conf.d/akim-dotfiles.conf par install.sh
# IMPORTANT : Current=akim uniquement (pas de chemin vers ~/akim-dotfiles)

[General]
DisplayServer=x11
GreeterEnvironment=QT_WAYLAND_DISABLE_WINDOWDECORATION=1,QML_DISABLE_DISK_CACHE=1
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=akim

[Wayland]
SessionDir=/usr/share/wayland-sessions
