general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 600                                 # 10 min — dim backlight
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 900                                 # 15 min — hyprlock + screen off
    on-timeout = ~/.config/hypr/scripts/idle-lock-screen.sh
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1200                                # 20 min — suspend
    on-timeout = systemctl suspend
}
